// Auto-generated by generate.js — do not edit manually
const portfolioData = [
  {
    "id": "08-04-2024",
    "name": "08-04-2024",
    "images": [
      "img/08-04-2024/foto20.webp",
      "img/08-04-2024/foto21.webp",
      "img/08-04-2024/foto22.webp",
      "img/08-04-2024/foto23.webp",
      "img/08-04-2024/foto24.webp"
    ],
    "cover": "img/08-04-2024/foto20.webp"
  },
  {
    "id": "09-04-2024",
    "name": "09-04-2024",
    "images": [
      "img/09-04-2024/foto25.webp"
    ],
    "cover": "img/09-04-2024/foto25.webp"
  },
  {
    "id": "26-01-2024",
    "name": "26-01-2024",
    "images": [
      "img/26-01-2024/foto1.webp",
      "img/26-01-2024/foto13.webp",
      "img/26-01-2024/foto2.webp",
      "img/26-01-2024/foto3.webp",
      "img/26-01-2024/foto6.webp",
      "img/26-01-2024/foto7.webp",
      "img/26-01-2024/foto8.webp",
      "img/26-01-2024/foto9.webp"
    ],
    "cover": "img/26-01-2024/foto1.webp"
  },
  {
    "id": "27-01-2024",
    "name": "27-01-2024",
    "images": [
      "img/27-01-2024/foto10.webp",
      "img/27-01-2024/foto11.webp",
      "img/27-01-2024/foto12.webp",
      "img/27-01-2024/foto4.webp",
      "img/27-01-2024/foto5.webp"
    ],
    "cover": "img/27-01-2024/foto10.webp"
  },
  {
    "id": "altro",
    "name": "Altro",
    "images": [
      "img/altro/foto14.webp",
      "img/altro/foto15.webp",
      "img/altro/foto16.webp",
      "img/altro/foto17.webp",
      "img/altro/foto18.webp",
      "img/altro/foto19.webp"
    ],
    "cover": "img/altro/foto14.webp"
  }
];
