// Auto-generated by generate.js — do not edit manually
var portfolioData = [
  {
    "id": "Bologna 14-07-2026",
    "name": "Bologna 14 07 2026",
    "images": [
      "img/Bologna 14-07-2026/Bologna-01.jpg",
      "img/Bologna 14-07-2026/Bologna-02.jpg",
      "img/Bologna 14-07-2026/Bologna-03.jpg",
      "img/Bologna 14-07-2026/Bologna-04.jpg",
      "img/Bologna 14-07-2026/Bologna-05.jpg",
      "img/Bologna 14-07-2026/Bologna-06.jpg",
      "img/Bologna 14-07-2026/Bologna-07.jpg",
      "img/Bologna 14-07-2026/Bologna-08.jpg",
      "img/Bologna 14-07-2026/Bologna-09.jpg",
      "img/Bologna 14-07-2026/Bologna-10.jpg",
      "img/Bologna 14-07-2026/Bologna-11.jpg",
      "img/Bologna 14-07-2026/Bologna-12.jpg",
      "img/Bologna 14-07-2026/Bologna-13.jpg",
      "img/Bologna 14-07-2026/Bologna-14.jpg",
      "img/Bologna 14-07-2026/Bologna-15.jpg"
    ],
    "thumbs": [
      "img/thumbs/Bologna 14-07-2026/Bologna-01.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-02.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-03.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-04.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-05.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-06.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-07.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-08.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-09.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-10.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-11.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-12.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-13.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-14.jpg",
      "img/thumbs/Bologna 14-07-2026/Bologna-15.jpg"
    ],
    "bwImages": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "orientations": [
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape"
    ],
    "cover": "img/Bologna 14-07-2026/Bologna-01.jpg",
    "coverThumb": "img/thumbs/Bologna 14-07-2026/Bologna-01.jpg"
  },
  {
    "id": "Ferrara 10-03-2026",
    "name": "Ferrara 10 03 2026",
    "images": [
      "img/Ferrara 10-03-2026/Ferrara-0.jpg",
      "img/Ferrara 10-03-2026/Ferrara-1.jpg",
      "img/Ferrara 10-03-2026/Ferrara-2.jpg",
      "img/Ferrara 10-03-2026/Ferrara-3.jpg",
      "img/Ferrara 10-03-2026/Ferrara-4.jpg",
      "img/Ferrara 10-03-2026/Ferrara-5.jpg",
      "img/Ferrara 10-03-2026/Ferrara-7.jpg",
      "img/Ferrara 10-03-2026/Ferrara-8.jpg"
    ],
    "thumbs": [
      "img/thumbs/Ferrara 10-03-2026/Ferrara-0.jpg",
      "img/thumbs/Ferrara 10-03-2026/Ferrara-1.jpg",
      "img/thumbs/Ferrara 10-03-2026/Ferrara-2.jpg",
      "img/thumbs/Ferrara 10-03-2026/Ferrara-3.jpg",
      "img/thumbs/Ferrara 10-03-2026/Ferrara-4.jpg",
      "img/thumbs/Ferrara 10-03-2026/Ferrara-5.jpg",
      "img/thumbs/Ferrara 10-03-2026/Ferrara-7.jpg",
      "img/thumbs/Ferrara 10-03-2026/Ferrara-8.jpg"
    ],
    "bwImages": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "orientations": [
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape"
    ],
    "cover": "img/Ferrara 10-03-2026/Ferrara-0.jpg",
    "coverThumb": "img/thumbs/Ferrara 10-03-2026/Ferrara-0.jpg"
  },
  {
    "id": "Padova 07-12-2025",
    "name": "Padova 07 12 2025",
    "images": [
      "img/Padova 07-12-2025/Cantante-0.jpg",
      "img/Padova 07-12-2025/Cantante-03.jpg",
      "img/Padova 07-12-2025/Cantante-04.jpg",
      "img/Padova 07-12-2025/Cantante-05.jpg",
      "img/Padova 07-12-2025/Cantante-06.jpg",
      "img/Padova 07-12-2025/Cantante-07.jpg",
      "img/Padova 07-12-2025/Cantante-08.jpg",
      "img/Padova 07-12-2025/Cantante-09.jpg"
    ],
    "thumbs": [
      "img/thumbs/Padova 07-12-2025/Cantante-0.jpg",
      "img/thumbs/Padova 07-12-2025/Cantante-03.jpg",
      "img/thumbs/Padova 07-12-2025/Cantante-04.jpg",
      "img/thumbs/Padova 07-12-2025/Cantante-05.jpg",
      "img/thumbs/Padova 07-12-2025/Cantante-06.jpg",
      "img/thumbs/Padova 07-12-2025/Cantante-07.jpg",
      "img/thumbs/Padova 07-12-2025/Cantante-08.jpg",
      "img/thumbs/Padova 07-12-2025/Cantante-09.jpg"
    ],
    "bwImages": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "orientations": [
      "landscape",
      "portrait",
      "portrait",
      "landscape",
      "portrait",
      "portrait",
      "portrait",
      "portrait"
    ],
    "cover": "img/Padova 07-12-2025/Cantante-0.jpg",
    "coverThumb": "img/thumbs/Padova 07-12-2025/Cantante-0.jpg"
  },
  {
    "id": "Padova 10-07-2026",
    "name": "Padova 10 07 2026",
    "images": [
      "img/Padova 10-07-2026/Padova-1.jpg",
      "img/Padova 10-07-2026/Padova-2.jpg",
      "img/Padova 10-07-2026/Padova-3.jpg",
      "img/Padova 10-07-2026/Padova-4.jpg",
      "img/Padova 10-07-2026/Padova-5.jpg",
      "img/Padova 10-07-2026/Padova-6.jpg",
      "img/Padova 10-07-2026/Padova-7.jpg",
      "img/Padova 10-07-2026/Padova-8.jpg",
      "img/Padova 10-07-2026/Padova-9.jpg"
    ],
    "thumbs": [
      "img/thumbs/Padova 10-07-2026/Padova-1.jpg",
      "img/thumbs/Padova 10-07-2026/Padova-2.jpg",
      "img/thumbs/Padova 10-07-2026/Padova-3.jpg",
      "img/thumbs/Padova 10-07-2026/Padova-4.jpg",
      "img/thumbs/Padova 10-07-2026/Padova-5.jpg",
      "img/thumbs/Padova 10-07-2026/Padova-6.jpg",
      "img/thumbs/Padova 10-07-2026/Padova-7.jpg",
      "img/thumbs/Padova 10-07-2026/Padova-8.jpg",
      "img/thumbs/Padova 10-07-2026/Padova-9.jpg"
    ],
    "bwImages": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "orientations": [
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape",
      "landscape"
    ],
    "cover": "img/Padova 10-07-2026/Padova-1.jpg",
    "coverThumb": "img/thumbs/Padova 10-07-2026/Padova-1.jpg"
  }
];

var singoleData = [
  {
    "src": "img/fotoSingole/Cantante-1.jpg",
    "thumb": "img/thumbs/fotoSingole/Cantante-1.jpg",
    "bwSrc": "img/fotoSingole/Cantante-1-BW.jpg",
    "bwThumb": "img/thumbs/fotoSingole/Cantante-1-BW.jpg",
    "orientation": "landscape"
  }
];
