// Auto-generated by generate.js — do not edit manually
var portfolioData = [
  {
    "id": "07-12-2025",
    "name": "07-12-2025",
    "images": [
      "img/07-12-2025/07-12-25-01.jpg",
      "img/07-12-2025/07-12-25-02.jpg",
      "img/07-12-2025/07-12-25-03.jpg",
      "img/07-12-2025/07-12-25-04.jpg",
      "img/07-12-2025/07-12-25-05.jpg",
      "img/07-12-2025/07-12-25-06.jpg",
      "img/07-12-2025/07-12-25-07.jpg",
      "img/07-12-2025/07-12-25-08.jpg",
      "img/07-12-2025/07-12-25-09.jpg",
      "img/07-12-2025/07-12-25-10.jpg",
      "img/07-12-2025/07-12-25-11.jpg",
      "img/07-12-2025/07-12-25-12.jpg",
      "img/07-12-2025/07-12-25-13.jpg"
    ],
    "thumbs": [
      "img/thumbs/07-12-2025/07-12-25-01.jpg",
      "img/thumbs/07-12-2025/07-12-25-02.jpg",
      "img/thumbs/07-12-2025/07-12-25-03.jpg",
      "img/thumbs/07-12-2025/07-12-25-04.jpg",
      "img/thumbs/07-12-2025/07-12-25-05.jpg",
      "img/thumbs/07-12-2025/07-12-25-06.jpg",
      "img/thumbs/07-12-2025/07-12-25-07.jpg",
      "img/thumbs/07-12-2025/07-12-25-08.jpg",
      "img/thumbs/07-12-2025/07-12-25-09.jpg",
      "img/thumbs/07-12-2025/07-12-25-10.jpg",
      "img/thumbs/07-12-2025/07-12-25-11.jpg",
      "img/thumbs/07-12-2025/07-12-25-12.jpg",
      "img/thumbs/07-12-2025/07-12-25-13.jpg"
    ],
    "bwImages": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "cover": "img/07-12-2025/07-12-25-01.jpg",
    "coverThumb": "img/thumbs/07-12-2025/07-12-25-01.jpg"
  },
  {
    "id": "10-03-2026",
    "name": "10-03-2026",
    "images": [
      "img/10-03-2026/10-03-2025-1.jpg",
      "img/10-03-2026/10-03-2025-2.jpg",
      "img/10-03-2026/10-03-2025-3.jpg",
      "img/10-03-2026/10-03-2025-4.jpg",
      "img/10-03-2026/10-03-2025-5.jpg",
      "img/10-03-2026/10-03-2025-6.jpg",
      "img/10-03-2026/10-03-2025-7.jpg",
      "img/10-03-2026/10-03-2025-8.jpg"
    ],
    "thumbs": [
      "img/thumbs/10-03-2026/10-03-2025-1.jpg",
      "img/thumbs/10-03-2026/10-03-2025-2.jpg",
      "img/thumbs/10-03-2026/10-03-2025-3.jpg",
      "img/thumbs/10-03-2026/10-03-2025-4.jpg",
      "img/thumbs/10-03-2026/10-03-2025-5.jpg",
      "img/thumbs/10-03-2026/10-03-2025-6.jpg",
      "img/thumbs/10-03-2026/10-03-2025-7.jpg",
      "img/thumbs/10-03-2026/10-03-2025-8.jpg"
    ],
    "bwImages": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "cover": "img/10-03-2026/10-03-2025-1.jpg",
    "coverThumb": "img/thumbs/10-03-2026/10-03-2025-1.jpg"
  },
  {
    "id": "10-07-2026",
    "name": "10-07-2026",
    "images": [
      "img/10-07-2026/WhatsApp Image 2026-07-10 at 21.51.41.jpeg",
      "img/10-07-2026/WhatsApp Image 2026-07-10 at 21.51.46.jpeg",
      "img/10-07-2026/WhatsApp Image 2026-07-10 at 21.51.55.jpeg",
      "img/10-07-2026/WhatsApp Image 2026-07-10 at 21.51.56.jpeg",
      "img/10-07-2026/WhatsApp Image 2026-07-10 at 21.53.35.jpeg"
    ],
    "thumbs": [
      "img/thumbs/10-07-2026/WhatsApp Image 2026-07-10 at 21.51.41.jpeg",
      "img/thumbs/10-07-2026/WhatsApp Image 2026-07-10 at 21.51.46.jpeg",
      "img/thumbs/10-07-2026/WhatsApp Image 2026-07-10 at 21.51.55.jpeg",
      "img/thumbs/10-07-2026/WhatsApp Image 2026-07-10 at 21.51.56.jpeg",
      "img/thumbs/10-07-2026/WhatsApp Image 2026-07-10 at 21.53.35.jpeg"
    ],
    "bwImages": [
      null,
      null,
      null,
      null,
      null
    ],
    "cover": "img/10-07-2026/WhatsApp Image 2026-07-10 at 21.51.41.jpeg",
    "coverThumb": "img/thumbs/10-07-2026/WhatsApp Image 2026-07-10 at 21.51.41.jpeg"
  },
  {
    "id": "25-04-2026",
    "name": "25-04-2026",
    "images": [
      "img/25-04-2026/25-04-2025-1.jpg",
      "img/25-04-2026/25-04-2025-2.jpg",
      "img/25-04-2026/25-04-2025-3.jpg",
      "img/25-04-2026/25-04-2025-4.jpg",
      "img/25-04-2026/25-04-2025-5.jpg"
    ],
    "thumbs": [
      "img/thumbs/25-04-2026/25-04-2025-1.jpg",
      "img/thumbs/25-04-2026/25-04-2025-2.jpg",
      "img/thumbs/25-04-2026/25-04-2025-3.jpg",
      "img/thumbs/25-04-2026/25-04-2025-4.jpg",
      "img/thumbs/25-04-2026/25-04-2025-5.jpg"
    ],
    "bwImages": [
      null,
      null,
      null,
      null,
      null
    ],
    "cover": "img/25-04-2026/25-04-2025-1.jpg",
    "coverThumb": "img/thumbs/25-04-2026/25-04-2025-1.jpg"
  }
];

var singoleData = [
  {
    "src": "img/fotoSingole/Cantante-1-2.jpg",
    "thumb": "img/thumbs/fotoSingole/Cantante-1-2.jpg",
    "bwSrc": null,
    "bwThumb": null
  },
  {
    "src": "img/fotoSingole/Cantante-1.jpg",
    "thumb": "img/thumbs/fotoSingole/Cantante-1.jpg",
    "bwSrc": "img/fotoSingole/Cantante-1-BW.jpg",
    "bwThumb": "img/thumbs/fotoSingole/Cantante-1-BW.jpg"
  },
  {
    "src": "img/fotoSingole/Cantante-2.jpg",
    "thumb": "img/thumbs/fotoSingole/Cantante-2.jpg",
    "bwSrc": null,
    "bwThumb": null
  }
];
