const fs = require('fs');
const path = require('path');

const imgDir = path.join(__dirname, 'img');
const thumbDir = path.join(__dirname, 'img', 'thumbs');

let sharp;
try {
  sharp = require('sharp');
} catch {
  console.warn('⚠ sharp non disponibile, thumbnail non generati. Esegui npm install');
}

const IMG_EXTS = /\.(webp|jpg|jpeg|png|gif|avif)$/i;
const THUMB_MAX = 800;
const HAS_SHARP = !!sharp;

function thumbUrl(origPath) {
  if (!HAS_SHARP) return origPath;
  return origPath.replace(/^img\//, 'img/thumbs/');
}

function formatName(folderName) {
  if (/^\d{2}-\d{2}-\d{4}$/.test(folderName)) return folderName;
  return folderName
    .split(/[-_]/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

async function ensureThumb(inputPath, outputPath) {
  if (!sharp) return inputPath;
  if (fs.existsSync(outputPath)) return outputPath;
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  try {
    await sharp(inputPath)
      .resize(THUMB_MAX, null, { fit: 'inside', withoutEnlargement: true })
      .toFile(outputPath);
  } catch (err) {
    console.warn(`  ⚠ thumbnail fallito: ${path.basename(inputPath)}`);
  }
  return outputPath;
}

function isBWFile(filename) {
  const ext = path.extname(filename);
  const base = path.basename(filename, ext);
  return /-BW$/i.test(base);
}

async function generate() {
  const entries = fs.readdirSync(imgDir, { withFileTypes: true });
  const folders = entries
    .filter(e => e.isDirectory() && e.name.toLowerCase() !== 'thumbs' && e.name.toLowerCase() !== 'fotosingole')
    .sort();

  // --- Folder data (existing behavior + thumbnails) ---
  const data = [];
  for (const folder of folders) {
    const folderPath = path.join(imgDir, folder.name);
    const files = fs.readdirSync(folderPath)
      .filter(f => IMG_EXTS.test(f))
      .sort();

    if (!files.length) continue;

    const colorFiles = files.filter(f => !isBWFile(f));
    const images = colorFiles.map(f => `img/${folder.name}/${f}`);
    const bwImages = colorFiles.map(f => {
      const ext = path.extname(f);
      const base = path.basename(f, ext);
      const bwFile = base + '-BW' + ext;
      return files.includes(bwFile) ? `img/${folder.name}/${bwFile}` : null;
    });

    for (const f of colorFiles) {
      await ensureThumb(
        path.join(imgDir, folder.name, f),
        path.join(thumbDir, folder.name, f)
      );
      const ext = path.extname(f);
      const base = path.basename(f, ext);
      const bwFile = base + '-BW' + ext;
      if (files.includes(bwFile)) {
        await ensureThumb(
          path.join(imgDir, folder.name, bwFile),
          path.join(thumbDir, folder.name, bwFile)
        );
      }
    }

    data.push({
      id: folder.name,
      name: formatName(folder.name),
      images,
      thumbs: images.map(f => thumbUrl(f)),
      bwImages,
      cover: images[0],
      coverThumb: thumbUrl(images[0])
    });
  }

  // --- FotoSingole data ---
  const singoleDir = path.join(imgDir, 'fotoSingole');
  let singoleData = [];

  if (fs.existsSync(singoleDir)) {
    const allFiles = fs.readdirSync(singoleDir).filter(f => IMG_EXTS.test(f)).sort();
    const bwFiles = allFiles.filter(f => isBWFile(f));
    const colorFiles = allFiles.filter(f => !isBWFile(f));

    for (const file of colorFiles) {
      const ext = path.extname(file);
      const base = path.basename(file, ext);
      const bwFile = base + '-BW' + ext;

      const src = `img/fotoSingole/${file}`;
      await ensureThumb(
        path.join(singoleDir, file),
        path.join(thumbDir, 'fotoSingole', file)
      );

      let bwSrc = null;
      let bwThumb = null;
      if (bwFiles.includes(bwFile)) {
        bwSrc = `img/fotoSingole/${bwFile}`;
        await ensureThumb(
          path.join(singoleDir, bwFile),
          path.join(thumbDir, 'fotoSingole', bwFile)
        );
        bwThumb = thumbUrl(bwSrc);
      }

      singoleData.push({
        src,
        thumb: thumbUrl(src),
        bwSrc,
        bwThumb
      });
    }
  }

  // --- Write output ---
  const output = `// Auto-generated by generate.js — do not edit manually
var portfolioData = ${JSON.stringify(data, null, 2)};

var singoleData = ${JSON.stringify(singoleData, null, 2)};
`;
  fs.writeFileSync(path.join(__dirname, 'js', 'data.js'), output);

  const imgCount = data.reduce((s, f) => s + f.images.length, 0);
  console.log(`✓ data.js generated: ${data.length} folders, ${imgCount} images, ${singoleData.length} singles`);
}

generate().catch(err => { console.error(err); process.exit(1); });
