const fs = require('fs');
const path = require('path');

const imgDir = path.join(__dirname, 'img');

function formatName(folderName) {
  if (/^\d{2}-\d{2}-\d{4}$/.test(folderName)) return folderName;
  return folderName
    .split(/[-_]/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function generate() {
  const entries = fs.readdirSync(imgDir, { withFileTypes: true });
  const folders = entries
    .filter(e => e.isDirectory())
    .sort();

  const data = folders.map(folder => {
    const folderPath = path.join(imgDir, folder.name);
    const files = fs.readdirSync(folderPath)
      .filter(f => /\.(webp|jpg|jpeg|png|gif|avif)$/i.test(f))
      .sort();

    const images = files.map(f => `img/${folder.name}/${f}`);

    return {
      id: folder.name,
      name: formatName(folder.name),
      images,
      cover: images[0] || ''
    };
  });

  const output = `// Auto-generated by generate.js — do not edit manually
var portfolioData = ${JSON.stringify(data, null, 2)};
`;
  fs.writeFileSync(path.join(__dirname, 'js', 'data.js'), output);
  console.log(`✓ data.js generated: ${data.length} folders, ${data.reduce((s, f) => s + f.images.length, 0)} images`);
}

generate();
